name: Scrape sauces

on:
  push:
    branches:
      - dev
    paths:
      - 'packages/scraper/**'
      - 'packages/db/**'
      - '.github/workflows/scrape.yml'
  workflow_dispatch:
    inputs:
      store:
        type: choice
        description: 'Select the store to scrape'
        required: true
        default: 'trex'
        options:
          - 'trex'
          - 'heatsupply'
          - 'heatonist'

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter "@app/db" install

      - name: Run scraper
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            # Run all scrapers on dev branch
            pnpm scrapers scrape trex --dbInsert
            pnpm scrapers scrape heatsupply --dbInsert
            pnpm scrapers scrape heatonist --dbInsert
          else
            # Run single scraper on manual trigger
            pnpm scrapers scrape ${{ github.event.inputs.store }} --dbInsert
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
